# This is a basic workflow to help you get started with Actions

name: PaperMC 1.16.5

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  building:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Building 1.16.5 Image
        run: cd 1.16.5 && docker build -t zombymediaic/papermc:1.16.5 . && cd ..


      # Runs a set of commands using the runners shell
      - name: Pushing 1.16.5 image
        run: docker push zombymediaic/papermc:1.16.5
