# This is a basic workflow to help you get started with Actions

name: PaperMC Check for Successfull build

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ development ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Validating:
    runs-on: ubuntu-latest
    steps:

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - uses: actions/checkout@v2

       # Runs a single command using the runners shell
      - name: Building 1.18.2 Image
        run: cd 1.18.2 && docker build -t zombymediaic/papermc:indev-1.18.2 . && cd ..

      # Runs a single command using the runners shell
      - name: Building 1.18.1 Image
        run: cd 1.18.1 && docker build -t zombymediaic/papermc:indev-1.18.1 . && cd ..

      # Runs a single command using the runners shell
      - name: Building 1.17.1 Image
        run: cd 1.17.1 && docker build -t zombymediaic/papermc:1.17.1 . && cd ..

      # Runs a single command using the runners shell
      - name: Building 1.17 Image
        run: cd 1.17 && docker build -t zombymediaic/papermc:1.17 . && cd ..

      # Runs a single command using the runners shell
      - name: Building 1.16.5-JAVA16 Image
        run: cd 1.16.5-java16 && docker build -t zombymediaic/papermc:1.16.5-java16 . && cd ..

      # Runs a single command using the runners shell
      - name: Building 1.16.5 Image
        run: cd 1.16.5 && docker build -t zombymediaic/papermc:1.16.5 . && cd ..

      # Runs a single command using the runners shell
      - name: Building 1.12.2 Image
        run: cd 1.12.2 && docker build -t zombymediaic/papermc:1.12.2 . && cd ..

      # Runs a single command using the runners shell
      - name: Building Waterfall Image
        run: cd waterfall-1.18 && docker build -t zombymediaic/papermc:waterfall-1.18 . && cd ..

      - name: Moving Card to Building
        uses: alex-page/github-project-automation-plus@v0.3.0
        with:
          project: BuildChecklist
          column: Ready for Build
          repo-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
